// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {devicemodel} from '../models';

export function ApplyDefaults():Promise<main.DeviceModelSnapshot>;

export function ApplyPreset(arg1:string):Promise<main.DeviceModelSnapshot>;

export function AttachRole(arg1:string,arg2:number,arg3:number,arg4:number):Promise<main.DeviceModelSnapshot>;

export function BuildAndFlash(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:boolean):Promise<void>;

export function CandidatePorts(arg1:string,arg2:string):Promise<Array<devicemodel.Port>>;

export function ClaimPort(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<main.DeviceModelSnapshot>;

export function Connect(arg1:string):Promise<main.ConnectionInfo>;

export function DetachRole(arg1:string,arg2:number,arg3:number):Promise<main.DeviceModelSnapshot>;

export function DeviceCapabilities():Promise<number>;

export function DeviceModelSnapshot():Promise<main.DeviceModelSnapshot>;

export function DeviceSystemInfo():Promise<main.DeviceInfo>;

export function DiagDebugEnabled():Promise<boolean>;

export function DiagLogPath():Promise<string>;

export function DiagSnapshot():Promise<Array<main.DiagEvent>>;

export function Disconnect():Promise<main.ConnectionInfo>;

export function DownloadConfig():Promise<string>;

export function DownloadEsptool():Promise<void>;

export function FlashFromRelease(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function FsDelete(arg1:string,arg2:string):Promise<void>;

export function FsDownloadToDisk(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FsList(arg1:string,arg2:string):Promise<Array<main.FsEntry>>;

export function FsMkdir(arg1:string,arg2:string):Promise<void>;

export function FsStorageStatus():Promise<main.FsStorageStatus>;

export function FsUploadBatch(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function FsUploadFromDisk(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetConnectionInfo():Promise<main.ConnectionInfo>;

export function GetFirmwareTargets():Promise<Array<main.FirmwareTarget>>;

export function GetFirmwareVersion(arg1:string):Promise<main.FirmwareVersionInfo>;

export function GetReleases(arg1:string):Promise<Array<main.ReleaseInfo>>;

export function GetToolsStatus():Promise<main.ToolsStatus>;

export function ListPorts():Promise<Array<main.PortInfo>>;

export function LogFrontend(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<void>;

export function OpenTextFile(arg1:string):Promise<main.OpenedFile>;

export function RefreshDeviceModel():Promise<main.DeviceModelSnapshot>;

export function SaveTextFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SendCommand(arg1:string):Promise<void>;

export function SetChannelFunction(arg1:string,arg2:number,arg3:number,arg4:number,arg5:string):Promise<main.DeviceModelSnapshot>;

export function SetDiagDebug(arg1:boolean):Promise<boolean>;

export function SetInputChannelCount(arg1:string,arg2:number,arg3:number,arg4:number):Promise<main.DeviceModelSnapshot>;

export function SetInputProtocol(arg1:string,arg2:number,arg3:number,arg4:string):Promise<main.DeviceModelSnapshot>;

export function SetPortName(arg1:string,arg2:number,arg3:number,arg4:string):Promise<main.DeviceModelSnapshot>;

export function UnclaimPort(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<main.DeviceModelSnapshot>;

export function UploadConfig(arg1:string):Promise<void>;
