// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {devicemodel} from '../models';
import {storage} from '../models';

export function ApplyDefaults():Promise<main.DeviceModelSnapshot>;

export function AttachRole(arg1:string,arg2:number,arg3:number,arg4:number):Promise<main.DeviceModelSnapshot>;

export function AudioPreloads():Promise<main.AudioPreloadStatus>;

export function BuildAndFlash(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:boolean):Promise<void>;

export function CandidatePorts(arg1:string,arg2:string):Promise<Array<devicemodel.Port>>;

export function CheckFiles(arg1:Array<string>):Promise<Array<main.FileCheck>>;

export function ClaimPort(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<main.DeviceModelSnapshot>;

export function Connect(arg1:string):Promise<main.ConnectionInfo>;

export function DeletePreset(arg1:string):Promise<void>;

export function DetachRole(arg1:string,arg2:number,arg3:number):Promise<main.DeviceModelSnapshot>;

export function DeviceCapabilities():Promise<number>;

export function DeviceModelSnapshot():Promise<main.DeviceModelSnapshot>;

export function DeviceSystemInfo():Promise<main.DeviceInfo>;

export function DiagBiMotorCalibrate(arg1:number,arg2:number,arg3:number):Promise<main.DiagCalibration>;

export function DiagBiMotorGuardFixed(arg1:number,arg2:number,arg3:number):Promise<void>;

export function DiagBiMotorGuardLiveRatio(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number):Promise<void>;

export function DiagBiMotorJog(arg1:number,arg2:number):Promise<void>;

export function DiagBiMotorMoveEnd(arg1:number,arg2:string,arg3:number,arg4:number):Promise<main.DiagEndstopResult>;

export function DiagBiMotorSeek(arg1:number,arg2:number,arg3:number):Promise<main.DiagEndstopResult>;

export function DiagBiMotorStatus(arg1:number):Promise<main.DiagBiMotorStatus>;

export function DiagBiMotorStop(arg1:number):Promise<void>;

export function DiagDebugEnabled():Promise<boolean>;

export function DiagInit():Promise<void>;

export function DiagLogPath():Promise<string>;

export function DiagRoleAttach(arg1:number,arg2:number,arg3:number):Promise<void>;

export function DiagRoleDetach(arg1:number,arg2:number):Promise<void>;

export function DiagRoleList():Promise<Array<main.DiagRole>>;

export function DiagServoProfileGet(arg1:number):Promise<main.DiagServoProfile>;

export function DiagServoSetTarget(arg1:number,arg2:number):Promise<void>;

export function DiagSnapshot():Promise<Array<main.DiagEvent>>;

export function Disconnect():Promise<main.ConnectionInfo>;

export function DownloadConfig():Promise<string>;

export function DownloadEsptool():Promise<void>;

export function EngineStart():Promise<void>;

export function EngineStatus():Promise<main.EngineStatusDTO>;

export function EngineStop():Promise<void>;

export function FlashFromRelease(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function FsDelete(arg1:string,arg2:string):Promise<void>;

export function FsDownloadToDisk(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FsList(arg1:string,arg2:string):Promise<Array<main.FsEntry>>;

export function FsMkdir(arg1:string,arg2:string):Promise<void>;

export function FsStorageStatus():Promise<main.FsStorageStatus>;

export function FsUploadBatch(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function FsUploadDiag():Promise<storage.UploadDiag>;

export function FsUploadFromDisk(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GearAll(arg1:number):Promise<void>;

export function GearDeploy(arg1:number):Promise<void>;

export function GearReset(arg1:number):Promise<void>;

export function GearRetract(arg1:number):Promise<void>;

export function GearStatus():Promise<Array<main.GearStatusEntry>>;

export function GearStop(arg1:number):Promise<void>;

export function GetConnectionInfo():Promise<main.ConnectionInfo>;

export function GetEngineConfig():Promise<main.EngineConfig>;

export function GetFirmwareTargets():Promise<Array<main.FirmwareTarget>>;

export function GetFirmwareVersion(arg1:string):Promise<main.FirmwareVersionInfo>;

export function GetInputRouting():Promise<boolean>;

export function GetLandingConfig():Promise<main.LandingConfigDTO>;

export function GetLightFxConfig():Promise<main.LightFxConfigDTO>;

export function GetLightFxProgram(arg1:string):Promise<string>;

export function GetLightFxProgramStructured(arg1:string):Promise<main.ProgramDTO>;

export function GetLightFxStatus():Promise<main.LightFxStatusDTO>;

export function GetReleases(arg1:string):Promise<Array<main.ReleaseInfo>>;

export function GetToolsStatus():Promise<main.ToolsStatus>;

export function GunFire(arg1:number):Promise<void>;

export function GunFireWithRof(arg1:number,arg2:number):Promise<void>;

export function GunFxStatus():Promise<Array<main.GunStatusDTO>>;

export function GunManualRelease(arg1:number):Promise<void>;

export function GunManualSet(arg1:number,arg2:main.GunManualStateDTO):Promise<void>;

export function GunSmokeArm(arg1:number,arg2:number):Promise<void>;

export function GunStartFiring(arg1:number,arg2:number):Promise<void>;

export function GunStartFiringWithRof(arg1:number,arg2:number,arg3:number):Promise<void>;

export function GunStopFiring(arg1:number):Promise<void>;

export function GunVerboseSubscribe(arg1:number,arg2:number):Promise<void>;

export function HeaterGetElement(arg1:number):Promise<main.HeaterElementDTO>;

export function HeaterSetElement(arg1:number,arg2:main.HeaterElementDTO):Promise<void>;

export function LandingActivate(arg1:number):Promise<void>;

export function LandingDeactivate(arg1:number):Promise<void>;

export function LandingStatus():Promise<Array<main.LandingStatusDTO>>;

export function ListAvailablePrograms():Promise<Array<main.ProgramFileInfo>>;

export function ListLightFxOrphans(arg1:Array<string>):Promise<Array<string>>;

export function ListPorts():Promise<Array<main.PortInfo>>;

export function ListPresetLibrary():Promise<Array<main.PresetLibraryEntry>>;

export function LoadGearConfig():Promise<main.GearConfig>;

export function LoadGunFxConfig():Promise<main.GunFxConfig>;

export function LoadHubConfig():Promise<void>;

export function LogFrontend(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<void>;

export function MotorGetElement(arg1:number):Promise<main.MotorElementDTO>;

export function MotorSetElement(arg1:number,arg2:main.MotorElementDTO):Promise<void>;

export function MotorSetPct(arg1:number,arg2:number):Promise<void>;

export function OpenTextFile(arg1:string):Promise<main.OpenedFile>;

export function PreviewLightChannel(arg1:number,arg2:number,arg3:boolean,arg4:Array<main.LightEventInput>):Promise<void>;

export function QueryDeviceStatus():Promise<main.DeviceStatus>;

export function RefreshDeviceModel():Promise<main.DeviceModelSnapshot>;

export function ResetLightFxProgram():Promise<void>;

export function SaveGearConfig(arg1:main.GearConfig):Promise<void>;

export function SaveGunFxConfig(arg1:main.GunFxConfig):Promise<void>;

export function SaveHubConfig():Promise<void>;

export function SavePresetAs(arg1:string,arg2:main.ProgramDTO):Promise<main.PresetLibraryEntry>;

export function SaveTextFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectLightFxProgram(arg1:string):Promise<void>;

export function SendCommand(arg1:string):Promise<void>;

export function ServoGetProfile(arg1:number):Promise<main.ServoProfileDTO>;

export function ServoSetProfile(arg1:number,arg2:main.ServoProfileDTO):Promise<void>;

export function ServoSetTarget(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetChannelFunction(arg1:string,arg2:number,arg3:number,arg4:number,arg5:string):Promise<main.DeviceModelSnapshot>;

export function SetDiagDebug(arg1:boolean):Promise<boolean>;

export function SetEngineConfig(arg1:main.EngineConfig):Promise<void>;

export function SetInputChannelCount(arg1:string,arg2:number,arg3:number,arg4:number):Promise<main.DeviceModelSnapshot>;

export function SetInputLiveView(arg1:boolean):Promise<void>;

export function SetInputProtocol(arg1:string,arg2:number,arg3:number,arg4:string):Promise<main.DeviceModelSnapshot>;

export function SetInputRouting(arg1:boolean):Promise<void>;

export function SetLandingConfig(arg1:main.LandingConfigDTO):Promise<void>;

export function SetLightFxConfig(arg1:main.LightFxConfigDTO):Promise<void>;

export function SetLightFxProgram(arg1:string,arg2:string):Promise<void>;

export function SetLightFxProgramStructured(arg1:string,arg2:main.ProgramDTO):Promise<void>;

export function SetPortName(arg1:string,arg2:number,arg3:number,arg4:string):Promise<main.DeviceModelSnapshot>;

export function SetPortProfile(arg1:string,arg2:number,arg3:number,arg4:main.ServoMotionProfileDTO):Promise<main.DeviceModelSnapshot>;

export function SetServoLiveView(arg1:boolean):Promise<void>;

export function StopLightChannel(arg1:number):Promise<void>;

export function SyncLightFxToDevice(arg1:main.LightFxConfigDTO,arg2:Array<main.ActiveProgramDTO>):Promise<void>;

export function UnclaimPort(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<main.DeviceModelSnapshot>;

export function UploadConfig(arg1:string):Promise<void>;
