// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyDefaults() {
  return window['go']['main']['App']['ApplyDefaults']();
}

export function AttachRole(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AttachRole'](arg1, arg2, arg3, arg4);
}

export function AudioPreloads() {
  return window['go']['main']['App']['AudioPreloads']();
}

export function BuildAndFlash(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['BuildAndFlash'](arg1, arg2, arg3, arg4, arg5);
}

export function CandidatePorts(arg1, arg2) {
  return window['go']['main']['App']['CandidatePorts'](arg1, arg2);
}

export function CheckFiles(arg1) {
  return window['go']['main']['App']['CheckFiles'](arg1);
}

export function ClaimPort(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ClaimPort'](arg1, arg2, arg3, arg4, arg5);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeletePreset(arg1) {
  return window['go']['main']['App']['DeletePreset'](arg1);
}

export function DetachRole(arg1, arg2, arg3) {
  return window['go']['main']['App']['DetachRole'](arg1, arg2, arg3);
}

export function DeviceCapabilities() {
  return window['go']['main']['App']['DeviceCapabilities']();
}

export function DeviceModelSnapshot() {
  return window['go']['main']['App']['DeviceModelSnapshot']();
}

export function DeviceSystemInfo() {
  return window['go']['main']['App']['DeviceSystemInfo']();
}

export function DiagBiMotorCalibrate(arg1, arg2, arg3) {
  return window['go']['main']['App']['DiagBiMotorCalibrate'](arg1, arg2, arg3);
}

export function DiagBiMotorGuardFixed(arg1, arg2, arg3) {
  return window['go']['main']['App']['DiagBiMotorGuardFixed'](arg1, arg2, arg3);
}

export function DiagBiMotorGuardLiveRatio(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['DiagBiMotorGuardLiveRatio'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DiagBiMotorJog(arg1, arg2) {
  return window['go']['main']['App']['DiagBiMotorJog'](arg1, arg2);
}

export function DiagBiMotorMoveEnd(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DiagBiMotorMoveEnd'](arg1, arg2, arg3, arg4);
}

export function DiagBiMotorSeek(arg1, arg2, arg3) {
  return window['go']['main']['App']['DiagBiMotorSeek'](arg1, arg2, arg3);
}

export function DiagBiMotorStatus(arg1) {
  return window['go']['main']['App']['DiagBiMotorStatus'](arg1);
}

export function DiagBiMotorStop(arg1) {
  return window['go']['main']['App']['DiagBiMotorStop'](arg1);
}

export function DiagDebugEnabled() {
  return window['go']['main']['App']['DiagDebugEnabled']();
}

export function DiagInit() {
  return window['go']['main']['App']['DiagInit']();
}

export function DiagLogPath() {
  return window['go']['main']['App']['DiagLogPath']();
}

export function DiagRoleAttach(arg1, arg2, arg3) {
  return window['go']['main']['App']['DiagRoleAttach'](arg1, arg2, arg3);
}

export function DiagRoleDetach(arg1, arg2) {
  return window['go']['main']['App']['DiagRoleDetach'](arg1, arg2);
}

export function DiagRoleList() {
  return window['go']['main']['App']['DiagRoleList']();
}

export function DiagServoProfileGet(arg1) {
  return window['go']['main']['App']['DiagServoProfileGet'](arg1);
}

export function DiagServoSetTarget(arg1, arg2) {
  return window['go']['main']['App']['DiagServoSetTarget'](arg1, arg2);
}

export function DiagSnapshot() {
  return window['go']['main']['App']['DiagSnapshot']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DownloadConfig() {
  return window['go']['main']['App']['DownloadConfig']();
}

export function DownloadEsptool() {
  return window['go']['main']['App']['DownloadEsptool']();
}

export function EngineStart() {
  return window['go']['main']['App']['EngineStart']();
}

export function EngineStatus() {
  return window['go']['main']['App']['EngineStatus']();
}

export function EngineStop() {
  return window['go']['main']['App']['EngineStop']();
}

export function FlashFromRelease(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FlashFromRelease'](arg1, arg2, arg3, arg4);
}

export function FsDelete(arg1, arg2) {
  return window['go']['main']['App']['FsDelete'](arg1, arg2);
}

export function FsDownloadToDisk(arg1, arg2, arg3) {
  return window['go']['main']['App']['FsDownloadToDisk'](arg1, arg2, arg3);
}

export function FsList(arg1, arg2) {
  return window['go']['main']['App']['FsList'](arg1, arg2);
}

export function FsMkdir(arg1, arg2) {
  return window['go']['main']['App']['FsMkdir'](arg1, arg2);
}

export function FsStorageStatus() {
  return window['go']['main']['App']['FsStorageStatus']();
}

export function FsUploadBatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['FsUploadBatch'](arg1, arg2, arg3);
}

export function FsUploadDiag() {
  return window['go']['main']['App']['FsUploadDiag']();
}

export function FsUploadFromDisk(arg1, arg2, arg3) {
  return window['go']['main']['App']['FsUploadFromDisk'](arg1, arg2, arg3);
}

export function GearAll(arg1) {
  return window['go']['main']['App']['GearAll'](arg1);
}

export function GearDeploy(arg1) {
  return window['go']['main']['App']['GearDeploy'](arg1);
}

export function GearReset(arg1) {
  return window['go']['main']['App']['GearReset'](arg1);
}

export function GearRetract(arg1) {
  return window['go']['main']['App']['GearRetract'](arg1);
}

export function GearStatus() {
  return window['go']['main']['App']['GearStatus']();
}

export function GearStop(arg1) {
  return window['go']['main']['App']['GearStop'](arg1);
}

export function GetConnectionInfo() {
  return window['go']['main']['App']['GetConnectionInfo']();
}

export function GetEngineConfig() {
  return window['go']['main']['App']['GetEngineConfig']();
}

export function GetFirmwareTargets() {
  return window['go']['main']['App']['GetFirmwareTargets']();
}

export function GetFirmwareVersion(arg1) {
  return window['go']['main']['App']['GetFirmwareVersion'](arg1);
}

export function GetInputRouting() {
  return window['go']['main']['App']['GetInputRouting']();
}

export function GetLandingConfig() {
  return window['go']['main']['App']['GetLandingConfig']();
}

export function GetLightFxConfig() {
  return window['go']['main']['App']['GetLightFxConfig']();
}

export function GetLightFxProgram(arg1) {
  return window['go']['main']['App']['GetLightFxProgram'](arg1);
}

export function GetLightFxProgramStructured(arg1) {
  return window['go']['main']['App']['GetLightFxProgramStructured'](arg1);
}

export function GetLightFxStatus() {
  return window['go']['main']['App']['GetLightFxStatus']();
}

export function GetReleases(arg1) {
  return window['go']['main']['App']['GetReleases'](arg1);
}

export function GetToolsStatus() {
  return window['go']['main']['App']['GetToolsStatus']();
}

export function GunFire(arg1) {
  return window['go']['main']['App']['GunFire'](arg1);
}

export function GunFireWithRof(arg1, arg2) {
  return window['go']['main']['App']['GunFireWithRof'](arg1, arg2);
}

export function GunFxStatus() {
  return window['go']['main']['App']['GunFxStatus']();
}

export function GunManualRelease(arg1) {
  return window['go']['main']['App']['GunManualRelease'](arg1);
}

export function GunManualSet(arg1, arg2) {
  return window['go']['main']['App']['GunManualSet'](arg1, arg2);
}

export function GunSmokeArm(arg1, arg2) {
  return window['go']['main']['App']['GunSmokeArm'](arg1, arg2);
}

export function GunStartFiring(arg1, arg2) {
  return window['go']['main']['App']['GunStartFiring'](arg1, arg2);
}

export function GunStartFiringWithRof(arg1, arg2, arg3) {
  return window['go']['main']['App']['GunStartFiringWithRof'](arg1, arg2, arg3);
}

export function GunStopFiring(arg1) {
  return window['go']['main']['App']['GunStopFiring'](arg1);
}

export function GunVerboseSubscribe(arg1, arg2) {
  return window['go']['main']['App']['GunVerboseSubscribe'](arg1, arg2);
}

export function HeaterGetElement(arg1, arg2) {
  return window['go']['main']['App']['HeaterGetElement'](arg1, arg2);
}

export function HeaterSetElement(arg1, arg2, arg3) {
  return window['go']['main']['App']['HeaterSetElement'](arg1, arg2, arg3);
}

export function LandingActivate(arg1) {
  return window['go']['main']['App']['LandingActivate'](arg1);
}

export function LandingDeactivate(arg1) {
  return window['go']['main']['App']['LandingDeactivate'](arg1);
}

export function LandingStatus() {
  return window['go']['main']['App']['LandingStatus']();
}

export function ListAvailablePrograms() {
  return window['go']['main']['App']['ListAvailablePrograms']();
}

export function ListLightFxOrphans(arg1) {
  return window['go']['main']['App']['ListLightFxOrphans'](arg1);
}

export function ListPorts() {
  return window['go']['main']['App']['ListPorts']();
}

export function ListPresetLibrary() {
  return window['go']['main']['App']['ListPresetLibrary']();
}

export function LoadGearConfig() {
  return window['go']['main']['App']['LoadGearConfig']();
}

export function LoadGunFxConfig() {
  return window['go']['main']['App']['LoadGunFxConfig']();
}

export function LoadHubConfig() {
  return window['go']['main']['App']['LoadHubConfig']();
}

export function LogFrontend(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LogFrontend'](arg1, arg2, arg3, arg4);
}

export function MotorGetElement(arg1, arg2) {
  return window['go']['main']['App']['MotorGetElement'](arg1, arg2);
}

export function MotorSetElement(arg1, arg2, arg3) {
  return window['go']['main']['App']['MotorSetElement'](arg1, arg2, arg3);
}

export function MotorSetPct(arg1, arg2, arg3) {
  return window['go']['main']['App']['MotorSetPct'](arg1, arg2, arg3);
}

export function OpenTextFile(arg1) {
  return window['go']['main']['App']['OpenTextFile'](arg1);
}

export function PreviewLightChannel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PreviewLightChannel'](arg1, arg2, arg3, arg4);
}

export function QueryDeviceStatus() {
  return window['go']['main']['App']['QueryDeviceStatus']();
}

export function RefreshDeviceModel() {
  return window['go']['main']['App']['RefreshDeviceModel']();
}

export function RemoveExpanderConfig(arg1) {
  return window['go']['main']['App']['RemoveExpanderConfig'](arg1);
}

export function ResetLightFxProgram() {
  return window['go']['main']['App']['ResetLightFxProgram']();
}

export function SaveGearConfig(arg1) {
  return window['go']['main']['App']['SaveGearConfig'](arg1);
}

export function SaveGunFxConfig(arg1) {
  return window['go']['main']['App']['SaveGunFxConfig'](arg1);
}

export function SaveHubConfig() {
  return window['go']['main']['App']['SaveHubConfig']();
}

export function SavePresetAs(arg1, arg2) {
  return window['go']['main']['App']['SavePresetAs'](arg1, arg2);
}

export function SaveTextFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2, arg3);
}

export function SelectLightFxProgram(arg1) {
  return window['go']['main']['App']['SelectLightFxProgram'](arg1);
}

export function SendCommand(arg1) {
  return window['go']['main']['App']['SendCommand'](arg1);
}

export function ServoGetProfile(arg1) {
  return window['go']['main']['App']['ServoGetProfile'](arg1);
}

export function ServoSetProfile(arg1, arg2) {
  return window['go']['main']['App']['ServoSetProfile'](arg1, arg2);
}

export function ServoSetTarget(arg1, arg2, arg3) {
  return window['go']['main']['App']['ServoSetTarget'](arg1, arg2, arg3);
}

export function SetChannelFunction(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetChannelFunction'](arg1, arg2, arg3, arg4, arg5);
}

export function SetDiagDebug(arg1) {
  return window['go']['main']['App']['SetDiagDebug'](arg1);
}

export function SetEngineConfig(arg1) {
  return window['go']['main']['App']['SetEngineConfig'](arg1);
}

export function SetInputChannelCount(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetInputChannelCount'](arg1, arg2, arg3, arg4);
}

export function SetInputLiveView(arg1) {
  return window['go']['main']['App']['SetInputLiveView'](arg1);
}

export function SetInputProtocol(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetInputProtocol'](arg1, arg2, arg3, arg4);
}

export function SetInputRouting(arg1) {
  return window['go']['main']['App']['SetInputRouting'](arg1);
}

export function SetLandingConfig(arg1) {
  return window['go']['main']['App']['SetLandingConfig'](arg1);
}

export function SetLightFxConfig(arg1) {
  return window['go']['main']['App']['SetLightFxConfig'](arg1);
}

export function SetLightFxProgram(arg1, arg2) {
  return window['go']['main']['App']['SetLightFxProgram'](arg1, arg2);
}

export function SetLightFxProgramStructured(arg1, arg2) {
  return window['go']['main']['App']['SetLightFxProgramStructured'](arg1, arg2);
}

export function SetPortName(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetPortName'](arg1, arg2, arg3, arg4);
}

export function SetPortProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetPortProfile'](arg1, arg2, arg3, arg4);
}

export function SetServoLiveView(arg1) {
  return window['go']['main']['App']['SetServoLiveView'](arg1);
}

export function StopLightChannel(arg1) {
  return window['go']['main']['App']['StopLightChannel'](arg1);
}

export function SyncLightFxToDevice(arg1, arg2) {
  return window['go']['main']['App']['SyncLightFxToDevice'](arg1, arg2);
}

export function UnclaimPort(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UnclaimPort'](arg1, arg2, arg3, arg4, arg5);
}

export function UploadConfig(arg1) {
  return window['go']['main']['App']['UploadConfig'](arg1);
}
