// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyDefaults() {
  return window['go']['main']['App']['ApplyDefaults']();
}

export function AttachRole(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AttachRole'](arg1, arg2, arg3, arg4);
}

export function BuildAndFlash(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['BuildAndFlash'](arg1, arg2, arg3, arg4, arg5);
}

export function CandidatePorts(arg1, arg2) {
  return window['go']['main']['App']['CandidatePorts'](arg1, arg2);
}

export function CheckFiles(arg1) {
  return window['go']['main']['App']['CheckFiles'](arg1);
}

export function ClaimPort(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ClaimPort'](arg1, arg2, arg3, arg4, arg5);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DetachRole(arg1, arg2, arg3) {
  return window['go']['main']['App']['DetachRole'](arg1, arg2, arg3);
}

export function DeviceCapabilities() {
  return window['go']['main']['App']['DeviceCapabilities']();
}

export function DeviceModelSnapshot() {
  return window['go']['main']['App']['DeviceModelSnapshot']();
}

export function DeviceSystemInfo() {
  return window['go']['main']['App']['DeviceSystemInfo']();
}

export function DiagDebugEnabled() {
  return window['go']['main']['App']['DiagDebugEnabled']();
}

export function DiagLogPath() {
  return window['go']['main']['App']['DiagLogPath']();
}

export function DiagSnapshot() {
  return window['go']['main']['App']['DiagSnapshot']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DownloadConfig() {
  return window['go']['main']['App']['DownloadConfig']();
}

export function DownloadEsptool() {
  return window['go']['main']['App']['DownloadEsptool']();
}

export function EngineStart() {
  return window['go']['main']['App']['EngineStart']();
}

export function EngineStatus() {
  return window['go']['main']['App']['EngineStatus']();
}

export function EngineStop() {
  return window['go']['main']['App']['EngineStop']();
}

export function FlashFromRelease(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FlashFromRelease'](arg1, arg2, arg3, arg4);
}

export function FsDelete(arg1, arg2) {
  return window['go']['main']['App']['FsDelete'](arg1, arg2);
}

export function FsDownloadToDisk(arg1, arg2, arg3) {
  return window['go']['main']['App']['FsDownloadToDisk'](arg1, arg2, arg3);
}

export function FsList(arg1, arg2) {
  return window['go']['main']['App']['FsList'](arg1, arg2);
}

export function FsMkdir(arg1, arg2) {
  return window['go']['main']['App']['FsMkdir'](arg1, arg2);
}

export function FsStorageStatus() {
  return window['go']['main']['App']['FsStorageStatus']();
}

export function FsUploadBatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['FsUploadBatch'](arg1, arg2, arg3);
}

export function FsUploadFromDisk(arg1, arg2, arg3) {
  return window['go']['main']['App']['FsUploadFromDisk'](arg1, arg2, arg3);
}

export function GetConnectionInfo() {
  return window['go']['main']['App']['GetConnectionInfo']();
}

export function GetEngineConfig() {
  return window['go']['main']['App']['GetEngineConfig']();
}

export function GetFirmwareTargets() {
  return window['go']['main']['App']['GetFirmwareTargets']();
}

export function GetFirmwareVersion(arg1) {
  return window['go']['main']['App']['GetFirmwareVersion'](arg1);
}

export function GetReleases(arg1) {
  return window['go']['main']['App']['GetReleases'](arg1);
}

export function GetToolsStatus() {
  return window['go']['main']['App']['GetToolsStatus']();
}

export function GunFire(arg1) {
  return window['go']['main']['App']['GunFire'](arg1);
}

export function GunFxStatus() {
  return window['go']['main']['App']['GunFxStatus']();
}

export function GunManualRelease(arg1) {
  return window['go']['main']['App']['GunManualRelease'](arg1);
}

export function GunManualSet(arg1, arg2) {
  return window['go']['main']['App']['GunManualSet'](arg1, arg2);
}

export function GunSmokeArm(arg1, arg2) {
  return window['go']['main']['App']['GunSmokeArm'](arg1, arg2);
}

export function GunStartFiring(arg1, arg2) {
  return window['go']['main']['App']['GunStartFiring'](arg1, arg2);
}

export function GunStopFiring(arg1) {
  return window['go']['main']['App']['GunStopFiring'](arg1);
}

export function GunVerboseSubscribe(arg1, arg2) {
  return window['go']['main']['App']['GunVerboseSubscribe'](arg1, arg2);
}

export function HeaterGetElement(arg1) {
  return window['go']['main']['App']['HeaterGetElement'](arg1);
}

export function HeaterSetElement(arg1, arg2) {
  return window['go']['main']['App']['HeaterSetElement'](arg1, arg2);
}

export function ListPorts() {
  return window['go']['main']['App']['ListPorts']();
}

export function LoadGunFxConfig() {
  return window['go']['main']['App']['LoadGunFxConfig']();
}

export function LoadHubConfig() {
  return window['go']['main']['App']['LoadHubConfig']();
}

export function LogFrontend(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LogFrontend'](arg1, arg2, arg3, arg4);
}

export function MotorGetElement(arg1) {
  return window['go']['main']['App']['MotorGetElement'](arg1);
}

export function MotorSetElement(arg1, arg2) {
  return window['go']['main']['App']['MotorSetElement'](arg1, arg2);
}

export function MotorSetPct(arg1, arg2) {
  return window['go']['main']['App']['MotorSetPct'](arg1, arg2);
}

export function OpenTextFile(arg1) {
  return window['go']['main']['App']['OpenTextFile'](arg1);
}

export function RefreshDeviceModel() {
  return window['go']['main']['App']['RefreshDeviceModel']();
}

export function SaveGunFxConfig(arg1) {
  return window['go']['main']['App']['SaveGunFxConfig'](arg1);
}

export function SaveHubConfig() {
  return window['go']['main']['App']['SaveHubConfig']();
}

export function SaveTextFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2, arg3);
}

export function SendCommand(arg1) {
  return window['go']['main']['App']['SendCommand'](arg1);
}

export function ServoGetProfile(arg1) {
  return window['go']['main']['App']['ServoGetProfile'](arg1);
}

export function ServoSetProfile(arg1, arg2) {
  return window['go']['main']['App']['ServoSetProfile'](arg1, arg2);
}

export function SetChannelFunction(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetChannelFunction'](arg1, arg2, arg3, arg4, arg5);
}

export function SetDiagDebug(arg1) {
  return window['go']['main']['App']['SetDiagDebug'](arg1);
}

export function SetEngineConfig(arg1) {
  return window['go']['main']['App']['SetEngineConfig'](arg1);
}

export function SetInputChannelCount(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetInputChannelCount'](arg1, arg2, arg3, arg4);
}

export function SetInputProtocol(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetInputProtocol'](arg1, arg2, arg3, arg4);
}

export function SetPortName(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetPortName'](arg1, arg2, arg3, arg4);
}

export function SetPortProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetPortProfile'](arg1, arg2, arg3, arg4);
}

export function UnclaimPort(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UnclaimPort'](arg1, arg2, arg3, arg4, arg5);
}

export function UploadConfig(arg1) {
  return window['go']['main']['App']['UploadConfig'](arg1);
}
