using ScaleFXStudio.Models;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace ScaleFXStudio.Services;

public class ConfigService
{
    private readonly IDeserializer _deserializer;
    private readonly ISerializer _serializer;

    public ConfigService()
    {
        _deserializer = new DeserializerBuilder()
            .WithNamingConvention(UnderscoredNamingConvention.Instance)
            .IgnoreUnmatchedProperties()
            .Build();

        _serializer = new SerializerBuilder()
            .WithNamingConvention(UnderscoredNamingConvention.Instance)
            .ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitNull)
            .Build();
    }

    public ScaleFXConfiguration Load(string filePath)
    {
        var yaml = File.ReadAllText(filePath);
        return _deserializer.Deserialize<ScaleFXConfiguration>(yaml) ?? new ScaleFXConfiguration();
    }

    public void Save(string filePath, ScaleFXConfiguration config)
    {
        var yaml = _serializer.Serialize(config);
        
        // Add header comment
        var header = """
            # ScaleFX Hub Configuration File
            # Generated by ScaleFX Studio Editor
            # See docs/README.md for configuration details
            
            """;
        
        File.WriteAllText(filePath, header + yaml);
    }

    public ScaleFXConfiguration CreateDefault()
    {
        return new ScaleFXConfiguration
        {
            EngineFx = new EngineFxConfig
            {
                Enabled = false,
                EngineToggle = new PwmInputConfig { InputChannel = 0, ThresholdUs = 1500 },
                Sounds = new EngineSoundsConfig
                {
                    Starting = "",
                    Running = "",
                    Stopping = "",
                    Transitions = new TransitionsConfig
                    {
                        StartingOffsetMs = 0,
                        StoppingOffsetMs = 0
                    }
                }
            },
            GunFx = new GunFxConfig
            {
                Enabled = false,
                Trigger = new TriggerConfig { InputChannel = 0 },
                Smoke = new SmokeConfig
                {
                    Enabled = false,
                    HeaterToggleChannel = 0,
                    HeaterPwmThresholdUs = 1500
                },
                TurretControl = new TurretControlConfig
                {
                    Pitch = new ServoConfig
                    {
                        Enabled = false,
                        ServoId = 0,
                        InputChannel = 0,
                        InputMinUs = 1000,
                        InputMaxUs = 2000,
                        OutputMinUs = 1000,
                        OutputMaxUs = 2000,
                        MaxSpeedUsPerSec = 500.0,
                        MaxAccelUsPerSec2 = 2000.0,
                        MaxDecelUsPerSec2 = 2000.0,
                        RecoilJerkUs = 0,
                        RecoilJerkVarianceUs = 0
                    },
                    Yaw = new ServoConfig
                    {
                        Enabled = false,
                        ServoId = 0,
                        InputChannel = 0,
                        InputMinUs = 1000,
                        InputMaxUs = 2000,
                        OutputMinUs = 1000,
                        OutputMaxUs = 2000,
                        MaxSpeedUsPerSec = 500.0,
                        MaxAccelUsPerSec2 = 2000.0,
                        MaxDecelUsPerSec2 = 2000.0,
                        RecoilJerkUs = 0,
                        RecoilJerkVarianceUs = 0
                    }
                },
                RateOfFire = new List<RateOfFireConfig>()
            }
        };
    }
}
